data:
  - "/mnt/data/shenyibo/workspace/q3_stack_cup/replay_buffer.zarr"
task:
  - "Stack all three cup together"
features:
  left_wrist_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  left_eye_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  right_eye_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [7,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [7,]
    names: ["actions"]